repository-header-update
StratusGrid/terraform-aws-interview-starter pull request #1
Opened 2024-04-08 21:51 UTC by jheison-rodriguez

## Change description

> Update header, and file names

## Type of change
- [x] Bug fix (fixes an issue)
- [x] New feature (adds functionality)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [x] Lint rules pass locally
- [x] Application changes have been tested thoroughly
- [x] Automated tests covering modified code pass

### Security

- [x] Security impact of change has been considered
- [x] Code follows company security practices and guidelines

### Code review 

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

2024-04-09 13:21 UTC, JoseMotto-sg requested changes

2024-04-09 13:21 UTC, JoseMotto-sg commented on versions.tf
> +      version = "5.44.0"
```suggestion
      version = ">= 5.44.0"
```

Don't lock the version

2024-04-09 21:08 UTC, jheison-rodriguez commented on versions.tf
> +      version = "5.44.0"
change commited

2024-04-10 14:24 UTC, JoseMotto-sg approved these changes
LGTM

2024-04-10 14:32 UTC, merged